### ISSUE TITLE
Cannot compile with 4.13 and up

### ISSUE THREAD

**Issue by VirtualLilies** [AndreaCatania/GoddessSoundVisualizer#1]
Any chance getting this compatible with 4.14 ? For some reason I cannot get it working even when building from source.

**Comment by kimba23** [comment]
Yes can you please update

**Comment by VirtualLilies** [comment]
Whenever I try to open up example project I get error saying the plugin is missing modules/is incompatible and asks me to disable it, if I go with "No" it starts loading up the project but then spits an error saying the modules are missing and closes the project.

After a second thought, it seems like it has to be installed in the engine and doesn't work from the project ?

**Comment by VirtualLilies** [comment]
Not matter how I try to use your plugin, it doesn't want to get build. Tried with fresh code project, tried with your example, tried with both 4.14 and 4.15. Any solution will be much appreciated.

> Running D:/Program Files (x86)/Epic Games/UE_4.14/Engine/Binaries/DotNET/UnrealBuildTool.exe SoundPlugin Development Win64 -project="D:/_Unreal Projects/SoundPlugin/SoundPlugin.uproject" -editorrecompile -progress -noubtmakefiles -NoHotReloadFromIDE
@progress push 5%
@progress pop
Performing 16 actions (4 in parallel)
[3/16] Resource PCLaunch.rc
[4/16] Resource ModuleVersionResource.rc.inl
GoddessSoundVisualizer.generated.cpp
Module.GoddessSoundVisualizer.cpp
Module.GoddessFrequencyImporter.cpp
PCH.SoundPlugin.h.cpp
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(34): error C2039: 'IsAudioComponentValid': is not a member of 'FActiveSound'
D:\Program Files (x86)\Epic Games\UE_4.14\Engine\Source\Runtime\Engine\Public\ActiveSound.h(129): note: see declaration of 'FActiveSound'
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(67): error C2664: 'FActiveSound *FAudioDevice::FindActiveSound(uint64)': cannot convert argument 1 from 'UAudioComponent *' to 'uint64'
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(67): note: There is no context in which this conversion is possible
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(90): error C2039: 'IsAudioComponentValid': is not a member of 'FActiveSound'
D:\Program Files (x86)\Epic Games\UE_4.14\Engine\Source\Runtime\Engine\Public\ActiveSound.h(129): note: see declaration of 'FActiveSound'
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(113): error C2664: 'FActiveSound *FAudioDevice::FindActiveSound(uint64)': cannot convert argument 1 from 'UAudioComponent *' to 'uint64'
D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Source\GoddessSoundVisualizer\Private\GoddessSoundVisualizer.cpp(113): note: There is no context in which this conversion is possible
GoddessFrequencyImporter.generated.cpp
[8/16] Resource PCLaunch.rc
[9/16] Resource ModuleVersionResource.rc.inl
[10/16] Resource PCLaunch.rc
[11/16] Resource ModuleVersionResource.rc.inl
SoundPlugin.cpp
EmptyClass.cpp
[14/16] Link UE4Editor-SoundPlugin.dll
   Creating library D:\_Unreal Projects\SoundPlugin\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-SoundPlugin.lib and object D:\_Unreal Projects\SoundPlugin\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-SoundPlugin.exp
ERROR: UBT ERROR: Failed to produce item: D:\_Unreal Projects\SoundPlugin\Plugins\GoddessSoundVisualizer\GoddessSoundVisualizer\Binaries\Win64\UE4Editor-GoddessSoundVisualizer.dll
Total build time: 77,16 seconds
LogInit:Warning: Still incompatible or missing module: UE4Editor-GoddessSoundVisualizer.dll
LogInit:Warning: Still incompatible or missing module: UE4Editor-GoddessSoundVisualizer.dll
LogInit:Warning: Still incompatible or missing module: UE4Editor-GoddessSoundVisualizer.dll
LogInit:Warning: Still incompatible or missing module: UE4Editor-GoddessFrequencyImporter.dll
LogInit:Warning: Still incompatible or missing module: UE4Editor-GoddessFrequencyImporter.dll
LogExit: Preparing to exit.

![image](https://cloud.githubusercontent.com/assets/11183246/24393684/476299c2-1399-11e7-8eb3-6e5fc1b661c4.png)

**Comment by AndreaCatania** [comment]
Few days ago I upgraded this plugin for UE4.16, Check It!
