### ISSUE TITLE
UU 4.16 Update

### ISSUE THREAD

**Issue by kamolesku** [AndreaCatania/GoddessSoundVisualizer#2]
Hello,

Thanks for this awesome plugin. I tried many others before (exi's soundvis and Windows Audio Capture) But yours works best!
Can you please update it to 4.16?

I am a sound designer and blueprint audio programmer I made this: https://www.youtube.com/watch?v=xgACek6ncAM

I need your plugin to make a prototype of a cool mechanic.

I have some assets on marketplace and on my disk I can offer you them, if you update it.

This is my e-mail: bartkamski@gmail.com

Thanks.

**Comment by AndreaCatania** [comment]
It works for 4.14, and as I've written on youtube I'm a bit stuck this period, but I really want port this for unreal 4.16 version. It requires some modifications since the engine has changed.

However your project is very interesting. Nice job!

**Comment by AndreaCatania** [comment]
I've updated the plugin to run ue4.16, check the section compile on readme file. Please let me know the use you do I'm just curious!!
