### ISSUE TITLE
Promote SoundFrequencySpectrum to Variable

### ISSUE THREAD

**Issue by kamolesku** [AndreaCatania/GoddessSoundVisualizer#3]
Hello!

Once again thank you for updating this plugin to 4.16. Me and my friend are making game prototype with it. It would be imposible without it. When we have some more i'll be happy to show you.

I like to ask you if it is possible to make a variable of SoundFrequencySpectrum? If so, how much work is it?

http://prntscr.com/fugh6a

Once again thank you for your awesome work!

**Comment by AndreaCatania** [comment]
Thanks you!

This is an easy step, that I've just done.
I've also added new Binaries for Win 64bit. Check it!

**Comment by kamolesku** [comment]
https://media.giphy.com/media/yoJC2El7xJkYCadlWE/giphy.gif
